spring:
#       ================================ | Configuração banco de dados  MySQL  |=================================
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
    driver-class-name: com.mysql.cj.jdbc.Driver
#       ================================ | Configuração banco de dados   |=======================================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
